technical_assessment:
  outputs:
    dev:
      dbname: airflow
      host: postgres
      pass: airflow
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: airflow
    duckdb:
      type: duckdb
      path: 'analytics.duckdb'
      schema: main
  target: dev
